spring:
  application:
    name: Pharmacy
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/PHARMACY
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dudkrish1A
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      continue-on-error: true
server:
  port: 8081
